#Goals:

#1 Scrape population data from wikipedia ' #done
#2 Process scraped data
#3 Interactive maps
#slider
#cartogram

#4 Animated maps

#Clearing environment before we begin
rm(list = ls())

#install.packages("hexmapmaker")

library(rayshader)
library(ggplot2)
library(dplyr)
library(rvest)
library(polite)
library(lubridate)
library(janitor)
library(httr)
library(gganimate)
library(gifski)
library(tweenr)
library(maps)
library(mapdata)
library(rnaturalearth)
library(rnaturalearthhires)
library(cartogram)
library(broom)
library(stringr)
library(sf)
library(viridis)
library(hexbin)

#Loading county gis data. 
#directories
gis_dir <- "C:/Users/alanw/OneDrive/Documents/data/gis"
dir(gis_dir)

county_sf<- sf::st_read(paste0(gis_dir, "/admin_counties"))%>%
  select("COUNTY")

#Need to union the 4 dublin council regions to generate the historical county
county_sf$geometry[county_sf$COUNTY == "DUBLIN"]<- county_sf%>%
  dplyr::filter(COUNTY == "DUBLIN")%>%
  sf::st_union()

county_sf$geometry[county_sf$COUNTY == "GALWAY"]<- county_sf%>%
  dplyr::filter(COUNTY == "GALWAY")%>%
  sf::st_union()

county_sf$geometry[county_sf$COUNTY == "CORK"]<- county_sf%>%
  dplyr::filter(COUNTY == "CORK")%>%
  sf::st_union()

county_sf<- county_sf%>%
  as.data.frame()%>%
  distinct()%>%
  st_as_sf()

#Polygons for the 26 historical counties
plot(county_sf)

#Scraping time series population data from wikipedia: 
#https://en.wikipedia.org/wiki/Historical_population_of_Ireland
url <- "https://en.wikipedia.org/wiki/Historical_population_of_Ireland"
#browseURL(url)
url_bow<- polite::bow(url)

ind_html <- polite::scrape(url_bow)%>%
  rvest::html_nodes("table.wikitable")%>%
  rvest::html_table(fill = TRUE)

titles <- polite::scrape(url_bow)%>%
  rvest::html_nodes("h3")%>%
  html_text()%>%
  substr(., 1, nchar(.)-6)%>%
  str_to_upper()

titles <- titles[-c(1:4)]

#Processing scraped data ready to mapping
counties_historical <- ind_html[c(7:38)]

for(i in 1:32){
counties_historical[[i]] <- counties_historical[[i]]%>%
  t()%>%
  as.data.frame()%>%
  dplyr::select(1)%>%
  dplyr::rename("population" = "V1")%>%
  slice(-1)%>%
  mutate(county = titles[i],
         year = row.names(.))%>%
  select(county, year, population)%>%
  mutate(population = str_remove(population, ","))
}

counties <- counties_historical%>%
  bind_rows()%>%
  filter(!is.na(population))%>%
  mutate(year = as.numeric(year),
         population = as.numeric(population))%>%
  filter(county %in% county_sf$COUNTY)%>%
  dplyr::rename("COUNTY"= "county")%>%
  left_join(., county_sf, by = "COUNTY")%>%
  st_as_sf()%>%
  st_simplify(., dTolerance = 100)

counties$year[counties$year == 1928] <- 1926
counties$year[counties$year == 1931] <- 1936

#Generating the time series visualisation
pop_change <- ggplot()+
  geom_sf(data =counties,
          aes(fill = population))+
  scale_fill_viridis(option = "B",
                     name = "Population \n1000s",
                     guide = guide_colorbar(
                       direction = "horizontal",
                       barheight = unit(2, units = "mm"),
                       barwidth = unit(100, units = "mm"),
                       draw.ulim = FALSE,
                       title.position = "top",
                       title.hjust = 0.5,
                       title.vjust = 0.5 ))+
  labs(title="Irish population by county",
       subtitle = paste0("Census year: ", "{current_frame}"),
       caption = "Generated by Alan Ward GIS")+
  transition_manual(year)+
  theme_classic()+
  theme(
    axis.line = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    axis.text = element_blank(),
    legend.position = "bottom"
  )

pop_animation <- animate(pop_change, 
        fps = 4, 
        height = 1000, 
        width = 700)

pop_animation

anim_save("irishPopMapChloropleth.gif", pop_animation)

###################################################

#Generating animated graph of same population change

####################################################

#Cartogram
pop_cart<- lapply(unique(counties$year), function (x) {
  cartogram::cartogram_cont(counties%>%
                                       filter(year == x),
                          weight = "population")%>%
    as.data.frame()
})%>%
  bind_rows()%>%
  st_as_sf()

#Generating the time series visualisation
pop_change <- 
  ggplot()+
  geom_sf(data =pop_cart,
          aes(fill = population))+
  scale_fill_viridis(option = "B",
                     name = "Population \n1000s",
                     guide = guide_colorbar(
                       direction = "horizontal",
                       barheight = unit(2, units = "mm"),
                       barwidth = unit(100, units = "mm"),
                       draw.ulim = FALSE,
                       title.position = "top",
                       title.hjust = 0.5,
                       title.vjust = 0.5 ))+
  labs(title="Irish population by county",
       subtitle = paste0("Census year: ", "{current_frame}"),
       caption = "Generated by Alan Ward GIS")+
  transition_manual(year)+
  theme_classic()+
  theme(
    axis.line = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    axis.text = element_blank(),
    legend.position = "bottom"
  )

pop_animation <- animate(pop_change, 
                         fps = 4, 
                         height = 1000, 
                         width = 700)

anim_save("irishPopMapChloroplethCartogram.gif", pop_animation)









################################################################################

#Experiment in ernest in a different script


# As a hexmap with SAs

################################################################################
# 
# #Turning polygons into centroids
# data_dir <- "C:/Users/alanw/OneDrive/Documents/data/cso"
# 
# 
# sa    <- sf::st_read(paste0(gis_dir, "/sa2022"))
# 
# saps22 <- read.csv(paste0(data_dir, "/census2022/sa_saps.csv"))%>%
#   dplyr::select("GUID", "GEOGID", "T1_1AGETT")%>%
#   filter(GUID != "IE0")%>%
#   rename("SA_PUB2022" = "GEOGID")%>%
#   left_join(sa, 
#             by = "SA_PUB2022",
#             keep = FALSE)%>%
#   st_as_sf()%>%
#   filter(!is.na(OBJECTID))%>%
#   mutate(pop_density = T1_1AGETT/SHAPE_Area)
# 
# sa_hex <- saps22%>%
#   mutate(cent = st_centroid(geometry))%>%
#   as.data.frame()%>%
#   dplyr::select("SA_PUB2022", "pop_density", "cent")%>%
#   st_as_sf()%>%
#   mutate(id = row.names(.))
#   
#   hex_coords <- do.call(rbind, st_geometry(sa_hex)) %>% 
#   as_tibble() %>% setNames(c("lon","lat"))%>%
#   mutate(id = row.names(.))
# 
# sa_hex <- sa_hex%>%
#     as.data.frame()%>%
#     dplyr::select(-cent)%>%
#     left_join(hex_coords, by = "id")
#   
# names(hex_coords)
# 
# ggplot(sa_hex, aes(x = lon, y = lat))+
#   stat_summary_hex(bins=100,
#                    aes(z = pop_density),
#                    fun = "sum", colour="grey")+
#   scale_fill_viridis(option = "A")+
#   theme_classic()+
#   theme(
#     axis.line = element_blank(),
#     axis.title = element_blank(),
#     axis.ticks = element_blank(),
#     axis.text = element_blank(),
#     legend.position = "bottom"
#   )
# 
# summary(sa_hex$pop_density)
# 

# With rayshader 3D effects

################################################################################

#Experiment in ernest within a different script!

################################################################################

#With rayshader, 3D

###################################################
# 
# gg_shp <- ggplot() +
#   geom_sf(data = counties%>%
#                    filter(year == 2022),
#           aes(fill = population))+
#   scale_fill_viridis() +
#   ggtitle('Changing Irish Population') +
#   theme_classic()+
#   theme(
#     axis.line = element_blank(),
#     axis.title = element_blank(),
#     axis.ticks = element_blank(),
#     axis.text = element_blank(),
#     legend.position = "bottom"
#   )
# 
# plot_gg(gg_shp, multicore = TRUE, width = 3, height = 3,
#         height_aes = "fill", 
#         shadow = FALSE,
#         
#         scale = 200, windowsize = c(1280, 720), zoom = 0.65, 
#         phi = 50, sunangle = 90, theta = 45)
# 
# render_highquality("pop_rayshader.png")
# 

####################################################


